name: deploy

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.1.0
      -
        name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x.x
      -
        name: build
        run: deno bundle --unstable index.ts index.js
      - 
        name: copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "index.js"
          target: "~/qqbot2/bot/database/app/"
          overwrite: true
      -
        name: restart docker
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          connect_timeout: 10s
          script: |
            cd ~/qqbot2/bot/database/ &&
            docker-compose restart bot